# -*- mode:python -*-

import os
Import("env")

commonSrcs = ["config.cpp", "galloc.cpp", "log.cpp"]
harnessSrcs = ["debug_harness.cpp"]

# By default, we compile all cpp files in libzsim.so. List the cpp files that
# should be excluded below (one per line and in order, to ease merges)
excludeSrcs = [
"fftoggle.cpp",
"dumptrace.cpp",
"sorttrace.cpp",
]
excludeSrcs += harnessSrcs

libEnv = env.Clone()

# Build libzsim.so
globSrcNodes = Glob("*.cpp")
libSrcs = [str(x) for x in globSrcNodes if str(x) not in excludeSrcs]
libSrcs = list(set(libSrcs))
libEnv.Program("zsim", libSrcs)

# Build tracing utilities
traceEnv = env.Clone()
traceEnv["OBJSUFFIX"] += "t"
traceEnv.Program("dumptrace", ["dumptrace.cpp", "access_tracing.cpp", "memory_hierarchy.cpp"] + commonSrcs)
traceEnv.Program("sorttrace", ["sorttrace.cpp", "access_tracing.cpp"] + commonSrcs)

# Build harness (static to make it easier to run across environments)
# NOTE(gaomy): with PinCRT we cannot build static as CRT only provides shared libs.
# env["LINKFLAGS"] += " --static "
# env["LIBS"] += ["c"] # required by wordexp in zsim harness
# env.Program("zsim", commonSrcs)

# # Build additional utilities below
# env.Program("fftoggle", ["fftoggle.cpp"] + commonSrcs)
